### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by sheepy1** [liuslevis/GYBootingProtection#1]
如果项目是使用纯代码构建 UI 的话，一般需要在`-application:didFinishLaunchingWithOptions:`方法中初始化`window`和`rootViewController`，用 swizzling 替换了该方法来处理 crash 是可以的，但如果要给用户一个提示框之后再处理的话就不好用`UIAlertViewController`了，`[self.window.rootViewController presentViewController:alertController animated:YES completion:nil]`的时候`self.window.rootViewController`还是`nil`。针对这种情况最好能在文档中给出说明呢。

整体思路很棒，多谢分享🙏

**Comment by sheepy1** [comment]
使用之后发现在处理 crash 的逻辑中先检查 JSPatch 更新再去删除磁盘上的文件特别容易把刚下载的 JSPatch 文件给删除了…… : )

**Comment by liuslevis** [comment]
1. This might help: http://stackoverflow.com/questions/25783282/how-to-create-an-empty-application-in-xcode-6-without-storyboard.   Fell free to Pull Request ：）
2. 如果有 JSPatch 更新， 期望是 JSPatch 能够修复，建议不用删文件了~

**Comment by sheepy1** [comment]
1、我不是不知道怎么用纯代码构建 UI 😂 是 GYBootingProtection 目前对不是用 info.plist 配置初始化 storyboard 的项目不太适用，具体的我提了个 p r。

2、了解了

**Comment by liuslevis** [comment]
感谢 PR
