### ISSUE TITLE
使用纯代码写界面时，弹不出提示框以及彩蛋?

### ISSUE THREAD

**Issue by panshimin1113** [liuslevis/GYBootingProtection#3]

**Comment by liuslevis** [comment]
PR  fd3bfe09df94efc06cfc17f666cbc54185e82957 是解决这个问题的，参考 Demo 可以解决吗？present 时对象是否为 nil？

**Comment by panshimin** [comment]
我把 Demo 中的 Main.stroyboard 删除之后就出现这个问题，同时当 crash 数超过最大值时，进入的是`- (void)applicationDidBecomeActive:(UIApplication *)application`，而没有进入 `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`函数。

**Comment by panshimin1113** [comment]
嗯，可以解决这个问题。3q。
