### ISSUE TITLE
如果登录才crash能修好么？

### ISSUE THREAD

**Issue by jacobjiangwei** [liuslevis/GYBootingProtection#9]
登录状态下，打开app就连续crash
修复，重新登录
再次crash。。。

**Comment by liuslevis** [comment]
可以修复的，只要连续 crash 的时间间隔在设定阈值内

**Comment by jacobjiangwei** [comment]
我的意思是程序就算恢复正常了，走登陆就是会因为代码不对而crash怎么办

**Comment by liuslevis** [comment]
目前能修复因 document library 中脏数据导致的 crash。
如果 app 有代码导致的必 crash 路径，需要自己发新版本修复。

**Comment by jacobjiangwei** [comment]
谢谢
